abstract final class DatabaseSchema {
  static const statements = <String>[
    '''CREATE TABLE IF NOT EXISTS horses (
      id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, image_path TEXT,
      breed TEXT, gender TEXT, color TEXT, chip_id TEXT, birth_date TEXT,
      owner_name TEXT, stable_location TEXT, health_status TEXT DEFAULT 'جيدة',
      notes TEXT, created_at TEXT DEFAULT (datetime('now','localtime')),
      updated_at TEXT DEFAULT (datetime('now','localtime')),
      ownership_type TEXT DEFAULT 'إيواء', subscriber_id INTEGER)''',
    '''CREATE TABLE IF NOT EXISTS health_records (
      id INTEGER PRIMARY KEY AUTOINCREMENT, horse_id INTEGER NOT NULL,
      record_type TEXT NOT NULL, title TEXT NOT NULL, description TEXT,
      vet_name TEXT, record_date TEXT NOT NULL, next_date TEXT, attachments TEXT,
      notes TEXT, image_path TEXT, created_at TEXT DEFAULT (datetime('now','localtime')), expense_id INTEGER,
      FOREIGN KEY (horse_id) REFERENCES horses(id) ON DELETE CASCADE)''',
    '''CREATE TABLE IF NOT EXISTS appointments (
      id INTEGER PRIMARY KEY AUTOINCREMENT, horse_id INTEGER NOT NULL,
      appointment_type TEXT NOT NULL, title TEXT NOT NULL, description TEXT,
      appointment_date TEXT NOT NULL, reminder_days INTEGER DEFAULT 3,
      status TEXT DEFAULT 'مجدول', notes TEXT, image_path TEXT,
      created_at TEXT DEFAULT (datetime('now','localtime')),
      FOREIGN KEY (horse_id) REFERENCES horses(id) ON DELETE CASCADE)''',
    '''CREATE TABLE IF NOT EXISTS farrier_records (
      id INTEGER PRIMARY KEY AUTOINCREMENT, horse_id INTEGER NOT NULL,
      last_visit TEXT, next_visit TEXT, shoe_type TEXT, farrier_name TEXT,
      cost REAL DEFAULT 0, notes TEXT, image_path TEXT,
      created_at TEXT DEFAULT (datetime('now','localtime')), expense_id INTEGER,
      FOREIGN KEY (horse_id) REFERENCES horses(id) ON DELETE CASCADE)''',
    '''CREATE TABLE IF NOT EXISTS expenses (
      id INTEGER PRIMARY KEY AUTOINCREMENT, horse_id INTEGER, category TEXT NOT NULL,
      amount REAL NOT NULL, expense_date TEXT NOT NULL, description TEXT, notes TEXT,
      created_at TEXT DEFAULT (datetime('now','localtime')), invoice_path TEXT, image_path TEXT,
      payer_type TEXT DEFAULT 'owner', is_paid INTEGER DEFAULT 1,
      affects_budget INTEGER DEFAULT 1, charge_to_subscriber INTEGER DEFAULT 0,
      debt_settled INTEGER DEFAULT 0,
      FOREIGN KEY (horse_id) REFERENCES horses(id) ON DELETE SET NULL)''',
    '''CREATE TABLE IF NOT EXISTS daily_notes (
      id INTEGER PRIMARY KEY AUTOINCREMENT, horse_id INTEGER NOT NULL,
      note_date TEXT NOT NULL, appetite TEXT, activity TEXT, behavior TEXT,
      symptoms TEXT, general_notes TEXT, image_path TEXT,
      created_at TEXT DEFAULT (datetime('now','localtime')),
      FOREIGN KEY (horse_id) REFERENCES horses(id) ON DELETE CASCADE)''',
    '''CREATE TABLE IF NOT EXISTS subscribers (
      id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, phone TEXT,
      subscription_type TEXT, duration TEXT, amount REAL DEFAULT 0, start_date TEXT,
      end_date TEXT, status TEXT DEFAULT 'نشط', payment_method TEXT,
      linked_owner TEXT, notes TEXT, member_code TEXT, is_vip INTEGER DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now','localtime')),
      updated_at TEXT DEFAULT (datetime('now','localtime')), image_path TEXT, horse_id INTEGER)''',
    '''CREATE TABLE IF NOT EXISTS subscription_history (
      id INTEGER PRIMARY KEY AUTOINCREMENT, subscriber_id INTEGER NOT NULL,
      subscription_number INTEGER DEFAULT 1, subscription_type TEXT, duration TEXT,
      amount REAL DEFAULT 0, start_date TEXT, end_date TEXT, status TEXT DEFAULT 'مكتمل',
      payment_method TEXT, notes TEXT,
      created_at TEXT DEFAULT (datetime('now','localtime')),
      FOREIGN KEY (subscriber_id) REFERENCES subscribers(id) ON DELETE CASCADE)''',
    'CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT)',
    '''CREATE TABLE IF NOT EXISTS daily_bookings (
      id INTEGER PRIMARY KEY AUTOINCREMENT, customer_name TEXT NOT NULL, phone TEXT,
      service_type TEXT NOT NULL, duration_minutes INTEGER NOT NULL,
      price REAL NOT NULL DEFAULT 0, booking_date TEXT NOT NULL, booking_time TEXT,
      notes TEXT, image_path TEXT, created_at TEXT DEFAULT (datetime('now','localtime')))''',
    '''CREATE TABLE IF NOT EXISTS payments (
      id INTEGER PRIMARY KEY AUTOINCREMENT, subscriber_id INTEGER NOT NULL,
      amount REAL NOT NULL, payment_date TEXT NOT NULL, payment_method TEXT, notes TEXT,
      created_at TEXT DEFAULT (datetime('now','localtime')),
      FOREIGN KEY (subscriber_id) REFERENCES subscribers(id) ON DELETE CASCADE)''',
    '''CREATE TABLE IF NOT EXISTS payment_invoices (
      id INTEGER PRIMARY KEY AUTOINCREMENT, payment_id INTEGER NOT NULL,
      invoice_path TEXT NOT NULL, created_at TEXT DEFAULT (datetime('now','localtime')),
      FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE CASCADE)''',
    '''CREATE TABLE IF NOT EXISTS financial_transactions (
      id INTEGER PRIMARY KEY AUTOINCREMENT, type TEXT NOT NULL DEFAULT 'expense',
      amount REAL NOT NULL DEFAULT 0, title TEXT NOT NULL DEFAULT '', description TEXT DEFAULT '',
      source_type TEXT NOT NULL DEFAULT 'manual', source_id INTEGER, subscriber_id INTEGER,
      horse_id INTEGER, category TEXT DEFAULT 'أخرى', payment_method TEXT,
      transaction_date TEXT NOT NULL, ref_type TEXT, ref_id INTEGER,
      affects_budget INTEGER DEFAULT 1, is_subscriber_debt INTEGER DEFAULT 0,
      debt_settled INTEGER DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now','localtime')),
      updated_at TEXT DEFAULT (datetime('now','localtime')))''',
    '''CREATE TABLE IF NOT EXISTS boarding_payments (
      id INTEGER PRIMARY KEY AUTOINCREMENT, horse_id INTEGER NOT NULL, room_number TEXT,
      amount REAL NOT NULL DEFAULT 0, payment_date TEXT NOT NULL, due_date TEXT,
      is_paid INTEGER DEFAULT 1, notes TEXT, image_path TEXT,
      created_at TEXT DEFAULT (datetime('now','localtime')),
      FOREIGN KEY (horse_id) REFERENCES horses(id) ON DELETE CASCADE)''',
    '''CREATE TABLE IF NOT EXISTS treatment_records (
      id INTEGER PRIMARY KEY AUTOINCREMENT, horse_id INTEGER NOT NULL,
      treatment_type TEXT, medicine_name TEXT, amount REAL NOT NULL DEFAULT 0,
      treatment_date TEXT NOT NULL, is_paid INTEGER DEFAULT 0, notes TEXT, image_path TEXT,
      payer_type TEXT DEFAULT 'stable', affects_budget INTEGER DEFAULT 1,
      charge_to_subscriber INTEGER DEFAULT 0, debt_settled INTEGER DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now','localtime')),
      FOREIGN KEY (horse_id) REFERENCES horses(id) ON DELETE CASCADE)''',
    '''CREATE TABLE IF NOT EXISTS stable_general_expenses (
      id INTEGER PRIMARY KEY AUTOINCREMENT, category TEXT NOT NULL,
      amount REAL NOT NULL DEFAULT 0, expense_date TEXT NOT NULL,
      description TEXT, notes TEXT, affects_budget INTEGER DEFAULT 1,
      created_at TEXT DEFAULT (datetime('now','localtime')))''',
    '''CREATE TABLE IF NOT EXISTS stable_income_records (
      id INTEGER PRIMARY KEY AUTOINCREMENT, source TEXT, amount REAL NOT NULL DEFAULT 0,
      income_date TEXT NOT NULL, description TEXT, notes TEXT,
      created_at TEXT DEFAULT (datetime('now','localtime')))''',
    '''CREATE TABLE IF NOT EXISTS boarding_contracts (
      id INTEGER PRIMARY KEY AUTOINCREMENT, subscriber_id INTEGER, horse_id INTEGER,
      horse_name TEXT, contract_text TEXT, signed_date TEXT NOT NULL,
      signature_path TEXT, created_at TEXT DEFAULT (datetime('now','localtime')),
      pdf_path TEXT DEFAULT '')''',
    'CREATE INDEX IF NOT EXISTS idx_ft_ref ON financial_transactions(ref_type, ref_id)',
    'CREATE INDEX IF NOT EXISTS idx_ft_date ON financial_transactions(transaction_date)',
    'CREATE INDEX IF NOT EXISTS idx_ft_type ON financial_transactions(type)',
    'CREATE INDEX IF NOT EXISTS idx_bp_horse ON boarding_payments(horse_id)',
    'CREATE INDEX IF NOT EXISTS idx_tr_horse ON treatment_records(horse_id)',
    'CREATE INDEX IF NOT EXISTS idx_bc_sub ON boarding_contracts(subscriber_id)',
  ];

  static const columns = <String, Set<String>>{
    'horses': {
      'name',
      'image_path',
      'breed',
      'gender',
      'color',
      'chip_id',
      'birth_date',
      'owner_name',
      'stable_location',
      'health_status',
      'notes',
      'ownership_type',
      'subscriber_id',
    },
    'health_records': {
      'horse_id',
      'record_type',
      'title',
      'description',
      'vet_name',
      'record_date',
      'next_date',
      'attachments',
      'notes',
      'image_path',
      'expense_id',
    },
    'appointments': {
      'horse_id',
      'appointment_type',
      'title',
      'description',
      'appointment_date',
      'reminder_days',
      'status',
      'notes',
      'image_path',
    },
    'farrier_records': {
      'horse_id',
      'last_visit',
      'next_visit',
      'shoe_type',
      'farrier_name',
      'cost',
      'notes',
      'image_path',
      'expense_id',
    },
    'expenses': {
      'horse_id',
      'category',
      'amount',
      'expense_date',
      'description',
      'notes',
      'invoice_path',
      'image_path',
      'payer_type',
      'is_paid',
      'affects_budget',
      'charge_to_subscriber',
      'debt_settled',
    },
    'daily_notes': {
      'horse_id',
      'note_date',
      'appetite',
      'activity',
      'behavior',
      'symptoms',
      'general_notes',
      'image_path',
    },
    'subscribers': {
      'name',
      'phone',
      'subscription_type',
      'duration',
      'amount',
      'start_date',
      'end_date',
      'status',
      'payment_method',
      'linked_owner',
      'notes',
      'image_path',
      'horse_id',
      'member_code',
      'is_vip',
    },
    'subscription_history': {
      'subscriber_id',
      'subscription_number',
      'subscription_type',
      'duration',
      'amount',
      'start_date',
      'end_date',
      'status',
      'payment_method',
      'notes',
    },
    'settings': {'key', 'value'},
    'daily_bookings': {
      'customer_name',
      'phone',
      'service_type',
      'duration_minutes',
      'price',
      'booking_date',
      'booking_time',
      'notes',
      'image_path',
    },
    'payments': {
      'subscriber_id',
      'amount',
      'payment_date',
      'payment_method',
      'notes',
    },
    'payment_invoices': {'payment_id', 'invoice_path'},
    'financial_transactions': {
      'type',
      'amount',
      'title',
      'description',
      'source_type',
      'source_id',
      'subscriber_id',
      'horse_id',
      'category',
      'payment_method',
      'transaction_date',
      'ref_type',
      'ref_id',
      'affects_budget',
      'is_subscriber_debt',
      'debt_settled',
    },
    'boarding_payments': {
      'horse_id',
      'room_number',
      'amount',
      'payment_date',
      'due_date',
      'is_paid',
      'notes',
      'image_path',
    },
    'treatment_records': {
      'horse_id',
      'treatment_type',
      'medicine_name',
      'amount',
      'treatment_date',
      'is_paid',
      'notes',
      'image_path',
      'payer_type',
      'affects_budget',
      'charge_to_subscriber',
      'debt_settled',
    },
    'stable_general_expenses': {
      'category',
      'amount',
      'expense_date',
      'description',
      'notes',
      'affects_budget',
    },
    'stable_income_records': {
      'source',
      'amount',
      'income_date',
      'description',
      'notes',
    },
    'boarding_contracts': {
      'subscriber_id',
      'horse_id',
      'horse_name',
      'contract_text',
      'signed_date',
      'signature_path',
      'pdf_path',
    },
  };
}
